modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPLv3"
[[mods]]
modId="lifeless"
version="${file.jarVersion}"
displayName="Lifeless"
logoFile="icon.png"
credits="Thanks marto for the idea"
authors="Favouriteless"
description='''
Limit the number of lives players have in a world with configurable effects after running out of lives, trading of lives, randomisation and more; this mod is designed primarily for servers.
'''
